### ISSUE TITLE
"Unable to create tunnel" on MacOS 15.0.1

### ISSUE THREAD

**Issue by aut0** [zakosaba/wireguard-macos-app#7]
I get this issue when I try to load a configuration file
![image](https://github.com/user-attachments/assets/fc07c8df-5fd1-4aae-8ecb-3436dca18870)

I tested the configuration file on another Mac with WireGuard from AppStore and had no issues.

**Comment by vaardan** [comment]
Hi, I'm not the original developer, so I have no idea what the issue might be. You should direct all questions regarding app not working to the original devs, although I don't know if there's a way to reach them (their git repo has issues disabled).

> I tested the configuration file on another Mac with WireGuard from AppStore and had no issues.

That probably has something to do with differences between the machines or the networks they're on, rather than the Wireguard apps.
